fix: error TS2353: Object literal may only specify known properties, and '"align-self"' does not exist in type 'Properties<string | number, string & {}>'.